Repository Y-CHILDREN/server, pull requests merged in 2024-10, with the labels that each got.

#9 ci: add pnpm-lock.yaml
  .gitignore
  pnpm-lock.yaml
Labels: 🚌 ci/cd

#11 폴더 구조 수정
  .prettierrc
  .vscode/settings.json
  package.json
  src/data/dtos/.keep
  src/data/integrations/prisma/schema.prisma
  src/data/repositoryImpls/.keep
  src/domain/entities/.keep
  src/domain/repositories/.keep
  src/index.ts
  src/presentation/controllers/pingController.ts
  src/presentation/routers/index.ts
  src/presentation/routers/pingRouter.ts
  src/tests/.keep
  tests/view.ts
  utils/view.ts
  views/view.ts
Labels: ♻️ refactor

#21 ci: add tsc github action
  .github/ISSUE_TEMPLATE/workflows/tsc.yml
Labels: 🚌 ci/cd

#22 fix: move workflows directory out
  .github/workflows/tsc.yml
Labels: 🚌 ci/cd

#13 클린 아키텍처 예시
  package.json
  src/data/converters/calculationConverter.ts
  src/data/dtos/.keep
  src/data/dtos/calculationData.ts
  src/data/repositoryImpls/.keep
  src/data/repositoryImpls/inMemoryCalculationRepositoryImpl.ts
  src/di.ts
  src/domain/entities/.keep
  src/domain/entities/calculationData.ts
  src/domain/repositories/.keep
  src/domain/repositories/calculationRepository.ts
  src/domain/services/calculationService.ts
  src/index.ts
  src/presentation/controllers/calculationController.ts
  src/presentation/routers/calculationRouter.ts
  src/presentation/routers/index.ts
  src/tests/.keep
  src/tests/data/converters/calculationDataConverter.test.ts
  src/tests/data/repositoryImpls/inMemoryCalculationRepositoryImpl.test.ts
  src/tests/domain/services/calculationService.test.ts
  tsconfig.json
  vitest.config.ts
Labels: 🖊️ feature

#23 ci: add test.yml
  .github/workflows/test.yml
Labels: 🚌 ci/cd

#24 Feature/tj/5
  package.json
  pnpm-lock.yaml
  src/data/integrations/passport/googleOAuth.ts
  src/data/integrations/passport/initPassport.ts
  src/data/integrations/passport/kakaoOAuth.ts
  src/data/integrations/passport/naverOAuth.ts
  src/data/repositorylmpls/localUserRepositoryImpl.ts
  src/data/repositorylmpls/userData.json
  src/domain/models/user.ts
  src/domain/models/userRepository.ts
  src/domain/services/userService.ts
  src/index.ts
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/googleRouter.ts
  src/presentation/routers/auth/kakaoRouter.ts
  src/presentation/routers/auth/naverRouter.ts
  src/presentation/routers/auth/userRouter.ts
  src/presentation/routers/authRouter.ts
  src/presentation/routers/index.ts
  src/tests/view.ts
Labels: 🖊️ feature

#17 Trip Schedule
  .github/ISSUE_TEMPLATE/📜-이슈-생성-템플릿.md
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/server.iml
  .idea/vcs.xml
  package.json
  pnpm-lock.yaml
  src/config/view.ts
  src/data/converters/tripScheduleConverter.ts
  src/data/dtos/trip/createTripDto.ts
  src/data/dtos/trip/tripScheduleResponseDto.ts
  src/data/repositoryImpls/inMemoryTripScheduleRepositoryImpl.ts
  src/data/repositoryImpls/inMemoryUserRepositoryImpl.ts
  src/domain/entities/UserDataDummy.ts
  src/domain/entities/tripSchedule.ts
  src/domain/repositories/tripScheduleRepository.ts
  src/domain/repositories/userRepositoryDummy.ts
  src/domain/services/tripScheduleService.ts
  src/domain/services/userServiceDummy.ts
  src/index.ts
  src/presentation/controllers/tripScheduleController.ts
  src/presentation/routers/tripScheduleRouter.ts
  src/public/view.ts
  src/tests/data/repositoryImpls/inMemoryTripScheduleRepositoryImpl.test.ts
  src/tests/domain/entities/tripScheduleData.test.ts
  src/tests/domain/services/tripScheduleService.test.ts
  src/tests/presentation/controllers/tripScheduleController.test.ts
  src/tests/presentation/routers/tripScheduleRouter.test.ts
  src/utils/view.ts
  src/views/view.ts
Labels: 🖊️ feature

#25 refact: move directory repositoryImpls
  src/data/integrations/passport/initPassport.ts
  src/data/repositoryImpls/localUserRepositoryImpl.ts
  src/data/repositoryImpls/userData.json
  src/presentation/controllers/userController.ts
Labels: ♻️ refactor

#33 feat : cors 적용 , 리다이렉트 url 수정
  src/index.ts
Labels: 🖊️ feature

#34 버그 수정 및 리다이렉트 url 수정
  src/di.ts
  src/domain/models/userRepository.ts
  src/domain/services/userService.ts
  src/index.ts
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/googleRouter.ts
  src/presentation/routers/auth/kakaoRouter.ts
  src/presentation/routers/auth/naverRouter.ts
Labels: 🐛 bug

#35 feat : s3에 유저의 이미지 업데이트 파일 저장 되도록 구현
  package.json
  pnpm-lock.yaml
  src/index.ts
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/googleRouter.ts
  src/presentation/routers/auth/userRouter.ts
  src/presentation/routers/index.ts
Labels: 🖊️ feature

#38 feat : userController에 findUserbyEmail ,findUserbyEmailAandProvider 생성
  src/data/integrations/passport/googleOAuth.ts
  src/data/integrations/passport/kakaoOAuth.ts
  src/data/integrations/passport/naverOAuth.ts
  src/data/repositoryImpls/localUserRepositoryImpl.ts
  src/domain/repositories/userRepository.ts
  src/domain/services/userService.ts
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/googleRouter.ts
  src/presentation/routers/auth/kakaoRouter.ts
  src/presentation/routers/auth/naverRouter.ts
  src/tests/domain/services/userService.test.ts
Labels: 🖊️ feature

#39 feat : findUserByEmail 라우터 추가
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/userRouter.ts
Labels: 🖊️ feature
