Repository Y-CHILDREN/server, pull requests merged in 2024-11, with the labels that each got.

#32 Add created_by to tripSchedule data.
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  src/data/converters/tripScheduleConverter.ts
  src/data/dtos/trip/createTripDto.ts
  src/data/dtos/trip/tripScheduleResponseDto.ts
  src/di.ts
  src/domain/entities/tripSchedule.ts
  src/domain/repositories/tripScheduleRepository.ts
  src/domain/services/tripScheduleService.ts
  src/presentation/controllers/tripScheduleController.ts
  src/tests/data/repositoryImpls/inMemoryTripScheduleRepositoryImpl.test.ts
  src/tests/domain/entities/tripScheduleData.test.ts
  src/tests/domain/services/tripScheduleService.test.ts
  src/tests/presentation/controllers/tripScheduleController.test.ts
  src/tests/presentation/routers/tripScheduleRouter.test.ts
Labels: 🖊️ feature

#48 refactor: create&response Data type modify
  src/data/converters/tripScheduleConverter.ts
  src/data/dtos/trip/createTripDto.ts
  src/data/dtos/trip/tripScheduleResponseDto.ts
  src/data/repositoryImpls/userData.json
  src/domain/entities/tripSchedule.ts
  src/domain/services/tripScheduleService.ts
  src/index.ts
  src/presentation/controllers/tripScheduleController.ts
  src/tests/data/repositoryImpls/inMemoryTripScheduleRepositoryImpl.test.ts
  src/tests/domain/entities/tripScheduleData.test.ts
  src/tests/domain/services/tripScheduleService.test.ts
  src/tests/presentation/controllers/tripScheduleController.test.ts
  src/tests/presentation/routers/tripScheduleRouter.test.ts
Labels: ♻️ refactor

#49 [여행 일정] User trip_history 및 CRUD 기능 구현
  src/data/repositoryImpls/inMemoryTripScheduleRepositoryImpl.ts
  src/data/repositoryImpls/inMemoryUserRepositoryImpl.ts
  src/data/repositoryImpls/localUserRepositoryImpl.ts
  src/di.ts
  src/domain/entities/UserDataDummy.ts
  src/domain/models/user.ts
  src/domain/repositories/tripScheduleRepository.ts
  src/domain/repositories/userRepository.ts
  src/domain/repositories/userRepositoryDummy.ts
  src/domain/services/tripScheduleService.ts
  src/domain/services/userServiceDummy.ts
  src/presentation/controllers/tripScheduleController.ts
  src/presentation/routers/tripScheduleRouter.ts
  src/tests/domain/services/tripScheduleService.test.ts
  src/tests/presentation/controllers/tripScheduleController.test.ts
Labels: 🖊️ feature

#53 [여행 일정] Trip data modification API
  src/data/converters/tripScheduleConverter.ts
  src/data/repositoryImpls/inMemoryTripScheduleRepositoryImpl.ts
  src/data/repositoryImpls/userData.json
  src/domain/services/tripScheduleService.ts
  src/presentation/controllers/tripScheduleController.ts
  src/presentation/routers/tripScheduleRouter.ts
  src/tests/domain/services/tripScheduleService.test.ts
Labels: 🖊️ feature

#52 로그아웃 기능 리팩토리
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/userRouter.ts
  src/presentation/routers/authRouter.ts
Labels: ♻️ refactor

#54 [유저정보 조회] 이메일로 유저 부분 검색.
  src/data/repositoryImpls/localUserRepositoryImpl.ts
  src/domain/repositories/userRepository.ts
  src/domain/services/userService.ts
  src/presentation/controllers/userController.ts
  src/presentation/routers/auth/userRouter.ts
Labels: 🖊️ feature

#55 fix: modified router findUsersByEmail
  src/domain/services/tripScheduleService.ts
  src/domain/services/userService.ts
  src/presentation/controllers/tripScheduleController.ts
  src/presentation/routers/auth/userRouter.ts
Labels: 🐛 bug

#57 유저검색 누락 코드 살리기
  src/presentation/routers/auth/userRouter.ts
Labels: 🚨 hotfix

#58 Feature/jh/1
  src/data/converters/tripEventConverter.ts
  src/data/dtos/event/tripEventDto.ts
  src/data/repositoryImpls/inMemoryTripEventRepositoryImpl.ts
  src/data/repositoryImpls/userData.json
  src/di.ts
  src/domain/entities/tripEvent.ts
  src/domain/repositories/tripEventRepository.ts
  src/domain/services/tripEventService.ts
  src/index.ts
  src/presentation/controllers/tripEventController.ts
  src/presentation/routers/index.ts
  src/presentation/routers/tripEventRouter.ts
  src/tests/domain/entities/tripEvent.test.ts
  src/tests/domain/entities/tripScheduleData.test.ts
  src/tests/domain/services/tripEventService.test.ts
  src/tests/presentation/controllers/tripEventController.test.ts
  src/tests/presentation/routers/tripEventRouter.test.ts
  vitest.config.ts
Labels: 🖊️ feature

#59 토큰 보이지 않도록 dto 적용
  src/data/dtos/user/userDto.ts
  src/data/repositoryImpls/localUserRepositoryImpl.ts
  src/domain/services/userService.ts
  src/tests/domain/services/userService.test.ts
Labels: 🖊️ feature

#63 refactor : cost 비용 타입 string to number 변경
  src/data/converters/tripEventConverter.ts
  src/data/repositoryImpls/userData.json
Labels: 🖊️ feature
